name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    collapse-after: 5
    labels: 
      - 'chore'
      - 'ci'
      - 'documentation'
      - 'refactor'
      - 'style'
      - 'test'
  - title: '⬆️ Dependencies'
    collapse-after: 5
    labels:
      - 'dependencies'
autolabeler:
  - label: 'bug'
    title:
      - '/bug/i'
  - label: 'chore'
    title:
    - '/chore/i'
  - label: 'ci'
    title:
    - '/ci/i'
  - label: 'dependencies'
    title:
      - 'Bumps'
      - '/deps/i'
  - label: 'documentation'
    title:
    - '/docs/i'
  - label: 'enhancement'
    title:
    - '/feat/i'
  - label: 'refactor'
    title:
    - '/refactor/i'
  - label: 'style'
    title:
    - '/style/i'
  - label: 'test'
    title:
    - '/test/i'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION