name: 'Stale Issues and PRs Caller'

on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write
  contents: read
  
jobs:
  call-reusable:
    uses: NathanaelGandhi/stale-reusable-workflows/.github/workflows/stale-reusable.yaml@main
    secrets:
      caller_token: ${{ secrets.GITHUB_TOKEN }}
